[package]
name = "rs-template"
version = "0.1.0"
authors = ["Austin Lucas Lake <git@austinlucaslake.com>"]
edition = "2021"
description = "Template repository for Rust projects"
readme = "README.md"
repository = "https://github.com/austinlucaslake/rs-template"
license = "MIT"

