name: 'Close stale issues and PR'

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'This issue is stale because it has been open 2 weeks with no activity. Remove stale label or comment or this will be closed in a week.'
          close-issue-message: 'This issue was closed because it has been stalled for a week with no activity.'
          stale-issue-label: 'stale-issue'

          stale-pr-message: 'This PR is stale because it has been open 2 weeks with no activity. Remove stale label or comment or this will be closed in a week.'
          close-pr-message: 'This PR was closed because it has been stalled for a week with no activity.'
          stale-pr-label: 'stale-pr'

          days-before-stale: 14
          days-before-close: 7
          days-before-pr-close: -1