name: 'Stale'

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'This issue is now stale because it has been open for two weeks with no activity. Remove the stale label or comment or this will be closed in a week.'
          close-issue-message: 'This issue was closed because there has been no activity in the past week.'
          stale-pr-message: 'This pull request is now stale because it has been open for two weeks with no activity. Remove the stale label or comment or this will be closed in a week.'
          close-pr-message: 'This pull request was closed because there has been no activity in the past week.'
          days-before-stale: 14
          days-before-close: 7
          days-before-pr-close: -1
